server:
  port: 8080

spring:
  application:
    name: chifir-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/chifir
    username: chifir
    password: chifir
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug